apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: hello-api
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: cch0124/hello-api
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
    - k8s/service.yaml
    defaultNamespace: default
profiles:
  - name: prod
    activation:
    - kubeContext: k3d-prod
    build:
      tagPolicy: 
        sha256: {}
      artifacts:
        - image: cch0124/hello-api-prod
          context: .
          docker:
            dockerfile: Dockerfile
            cacheFrom:
            - "maven:3.5.2-jdk-8-alpine"
            - "adoptopenjdk/openjdk11:jre-11.0.10_9-alpine"
    deploy:
      kubeContext: k3d-prod
  - name: stage
    activation:
    - kubeContext: k3d-stage
    build:
      artifacts:
        - image: cch0124/hello-api-stage
          custom:
            buildCommand: docker build -t cch0124/hello-api-stage:latest . 
            dependencies:
              paths:
                - "src/**/*"
                - "pom.xml"
              ignore:
                - k8s/**/*.yaml
      local:
        push: false
