apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: skaffold-demo
build:
  tagPolicy:
    sha256: {}
    # gitCommit:
    #   variant: AbbrevCommitSha
    #   ignoreChanges: false
  artifacts:
  - image: cch0124/spring-tutorial-api
    custom:
      buildCommand: mvn compile jib:build -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD -Dimage=$IMAGE
      dependencies:
        paths:
        - src/**
    # jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deploy-native/tutorial/application-properties-cm.yaml
    - k8s/deploy-native/tutorial/deployment.yaml
    - k8s/deploy-native/tutorial/globalenv-cm.yaml
    - k8s/deploy-native/tutorial/globalenv-secret.yaml
    - k8s/deploy-native/tutorial/ingress.yaml
    - k8s/deploy-native/tutorial/service.yaml
profiles:
- name: dev-cluster
  activation:
  - env: ENV=dev
  - kubeContext: kubernetes-admin@kubernetes
    command: dev
