apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: skaffold-demo
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: cch0124/spring-tutorial-api
    custom:
      buildCommand: mvn compile jib:build -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD -Dimage=$IMAGE
      dependencies:
        paths:
        - src/**
deploy:
  kubectl:
    manifests:
    - k8s/deploy-native/tutorial/application-properties-cm.yaml
    - k8s/deploy-native/tutorial/deployment.yaml
    - k8s/deploy-native/tutorial/globalenv-cm.yaml
    - k8s/deploy-native/tutorial/globalenv-secret.yaml
    - k8s/deploy-native/tutorial/ingress.yaml
    - k8s/deploy-native/tutorial/service.yaml
profiles:
- name: dev-cluster
  activation:
  - env: ENV=dev
  - kubeContext: kubernetes-admin@kubernetes
    command: dev
- name: docker
  build:
    tagPolicy:
      customTemplate:
        template: "{{.FOO}}_{{.BAR}}-docker"
        components:
          - name: FOO
            dateTime:
              format: "2006-01-02"
              timezone: "UTC"
          - name: BAR
            gitCommit:
              variant: AbbrevCommitSha
    artifacts:
      - image: spring-tutorial-api
        context: .
        docker:
          dockerfile: Dockerfile
          cacheFrom:
            - spring-tutorial-api
    local:
      push: true
      useDockerCLI: false
      useBuildkit: false
- name: test
  test:
    - image: docker.io/cch0124/spring-tutorial-api
      custom:
        - command: mvn test -Dmaven.test.skip=false
- name: sync
  build:
    tagPolicy:
      customTemplate:
        template: "{{.DATE}}_{{.SHA}}-sync"
        components:
          - name: DATE
            dateTime:
              format: "2006-01-02"
              timezone: "UTC"
          - name: SHA
            gitCommit:
              variant: AbbrevCommitSha
    artifacts:
      - image: docker.io/cch0124/spring-tutorial-api
        context: .
        jib:
          type: maven
          args:
            - -Psync
        sync:
          auto: true
- name: userDefinedPortForward
  portForward:
    - localPort: 9090
      port: 8080
      namespace: default
      resourceName: tutorial-api-service
      resourceType: service
- name: jib
  build:
    tagPolicy:
      customTemplate:
        template: "{{.SHA}}-jib"
        components:
          - name: SHA
            gitCommit:
              variant: AbbrevCommitSha
    artifacts:
      - image: docker.io/cch0124/spring-tutorial-api
        context: .
        jib:
          type: maven
          fromImage: adoptopenjdk:16-jre
          project: cch.com.example:skaffold
          args:
            - -DskipTests
- name: jibWithHelm
  build:
    tagPolicy:
      customTemplate:
        template: "{{.SHA}}-jibWithHelm"
        components:
          - name: SHA
            gitCommit:
              variant: AbbrevCommitSha
    artifacts:
      - image: cch0124/spring-tutorial-api # must match in setValueTemplates
        context: .
        jib:
          type: maven
          fromImage: adoptopenjdk:16-jre
          project: cch.com.example:skaffold
          args:
            - -DskipTests
  deploy:
    helm:
      releases:
        - name: spring-tutorial-api
          chartPath: k8s/helm/tutorial
          setValueTemplates:
            image.repository: "{{.IMAGE_REPO_cch0124_spring_tutorial_api}}"
            image.tag: "{{.IMAGE_TAG_cch0124_spring_tutorial_api}}"
          setValues:
            replicaCount: "2"
          valuesFiles:
            - "k8s/helm/env/values-dev.yaml"
    kubeContext: kubernetes-admin@kubernetes