apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: skaffold-demo
build:
  artifacts:
  - image: cch0124/spring-tutorial-api
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deploy-native/tutorial/application-properties-cm.yaml
    - k8s/deploy-native/tutorial/deployment.yaml
    - k8s/deploy-native/tutorial/globalenv-cm.yaml
    - k8s/deploy-native/tutorial/globalenv-secret.yaml
    - k8s/deploy-native/tutorial/ingress.yaml
    - k8s/deploy-native/tutorial/service.yaml
