apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev
commonLabels:
  owner: CCH
commonAnnotations:
  env: dev
bases:
  - ../../base
patchesStrategicMerge:
  - ingress_path.yaml
  - resource_limit.yaml