apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
commonLabels:
  owner: CCH
commonAnnotations:
  env: prod
bases:
  - ../../base
resources:
  - namespace.yaml
patchesStrategicMerge:
  - ingress_path.yaml
  - resource_limit.yaml