apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tutorial.fullname" . }}
  labels:
    {{- include "tutorial.labels" . | nindent 4 }}
{{- if .Values.controller.configAnnotations }}
  annotations: {{ toYaml .Values.configAnnotations | nindent 4 }}
{{- end }}
data:
  application.properties: |-
  {{ .Values.application.config | indent 4 }}