apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tutorial.fullname" . }}-global-secret
  labels:
    {{- include "tutorial.labels" . | nindent 4 }}
data:
   # MTIzNDU2Nzg5MA==
   DB_PASSWORD: {{ required "Postgresql db password is required!" .Values.postgresql.password | b64enc }}
   # dev
   DB_USER: {{ required "Postgresql db user is required!" .Values.postgresql.user | b64enc }}
type: Opaque