apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tutorial.fullname" . }}-global
  labels:
    {{- include "tutorial.labels" . | nindent 4 }}
data:
  DB_URL: {{ required "Postgresql db url is required!" .Values.postgresql.url }}

